name: Sync PDF Files

on:
  push:
    branches:
      - main
  schedule:
    # - cron: "30 */4 * * *"
    - cron: "*/30 * * * *"
    - cron: "0 10 * * 2"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    env:
      USER: ${{ github.repository_owner }}
      REPO_CODE: ${{ vars.REPO_CODE }}
      PATH_CODE: code
      REPO_DATA: ${{ vars.REPO_DATA }}
      PATH_DATA: data
      COUNT_DATA: ${{ vars.COUNT_DATA || 10 }}
      COUNT_STOCK: ${{ vars.COUNT_STOCK || 10 }}
      COUNT_EXTRA: ${{ vars.COUNT_EXTRA || 0 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Generate Token1
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.HPW_APP_CLIENT_ID }}
          private-key: ${{ secrets.HPW_APP_PRIVATE_KEY }}
          owner: ${{ secrets.HPW_REPO }}

      - name: Register token
        run: |
          echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token
          gh auth setup-git

      - name: Generate Token2
        id: app-token2
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ env.USER }}
          repositories: ${{ env.REPO_CODE }},${{ env.REPO_DATA }}

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_CODE }}
          path: ${{ env.PATH_CODE }}
          token: ${{ steps.app-token2.outputs.token }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Checkout Data
        if: github.event.schedule != '0 10 * * 2'
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_DATA }}
          path: ${{ env.PATH_DATA }}
          token: ${{ steps.app-token2.outputs.token }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Python Env
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          working-directory: ${{ env.PATH_CODE }}

      - name: Run Incremental mode
        if: github.event.schedule != '0 10 * * 2'
        run: |
          pushd $PATH_CODE &&
          bash scripts/run-sync-files.sh \
              -f pdf -m inc \
              -c $COUNT_DATA \
              --base-dir .. --meta-dir ../$PATH_DATA
          popd

      - name: Run stock mode
        if: github.event.schedule == '0 10 * * 2'
        run: |
          pushd $PATH_CODE &&
          bash scripts/run-sync-files.sh \
              -f pdf -m stock \
              -c $COUNT_STOCK -e $COUNT_EXTRA \
              --base-dir .. --meta-dir ../$PATH_DATA
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
